// swift-tools-version: 6.3

import PackageDescription

// BEGIN OPENSSL SOURCE MANIFEST
// OpenSSL source manifest SHA-256: b502af822741fbc662c993894a65ff3f31167f32f709e5b3f1972f7ca17fdd17
let opensslSourcePaths: [String] = [
    "crypto",
    "providers",
    "ssl",
]
let opensslExcludedPaths: [String] = [
    "crypto/LPdir_nyi.inc",
    "crypto/LPdir_unix.inc",
    "crypto/LPdir_vms.inc",
    "crypto/LPdir_win.inc",
    "crypto/LPdir_win32.inc",
    "crypto/LPdir_wince.inc",
    "crypto/des/ncbc_enc.inc",
    "providers/decoders.inc",
    "providers/encoders.inc",
    "providers/fips/include/fips_indicator_params.inc",
    "providers/fips/include/fips_selftest_params.inc",
    "providers/implementations/asymciphers/rsa_enc.inc",
    "providers/implementations/asymciphers/sm2_enc.inc",
    "providers/implementations/ciphers/cipher_aes_cbc_hmac_sha.inc",
    "providers/implementations/ciphers/cipher_aes_cbc_hmac_sha_etm.inc",
    "providers/implementations/ciphers/cipher_aes_ccm_hw_aesni.inc",
    "providers/implementations/ciphers/cipher_aes_ccm_hw_rv32i.inc",
    "providers/implementations/ciphers/cipher_aes_ccm_hw_rv64i.inc",
    "providers/implementations/ciphers/cipher_aes_ccm_hw_s390x.inc",
    "providers/implementations/ciphers/cipher_aes_ccm_hw_t4.inc",
    "providers/implementations/ciphers/cipher_aes_cfb_hw_aesni.inc",
    "providers/implementations/ciphers/cipher_aes_cfb_hw_s390x.inc",
    "providers/implementations/ciphers/cipher_aes_cts.inc",
    "providers/implementations/ciphers/cipher_aes_gcm_hw_aesni.inc",
    "providers/implementations/ciphers/cipher_aes_gcm_hw_armv8.inc",
    "providers/implementations/ciphers/cipher_aes_gcm_hw_ppc.inc",
    "providers/implementations/ciphers/cipher_aes_gcm_hw_rv32i.inc",
    "providers/implementations/ciphers/cipher_aes_gcm_hw_rv64i.inc",
    "providers/implementations/ciphers/cipher_aes_gcm_hw_s390x.inc",
    "providers/implementations/ciphers/cipher_aes_gcm_hw_t4.inc",
    "providers/implementations/ciphers/cipher_aes_gcm_hw_vaes_avx512.inc",
    "providers/implementations/ciphers/cipher_aes_gcm_siv.inc",
    "providers/implementations/ciphers/cipher_aes_hw_aesni.inc",
    "providers/implementations/ciphers/cipher_aes_hw_armv8.inc",
    "providers/implementations/ciphers/cipher_aes_hw_rv32i.inc",
    "providers/implementations/ciphers/cipher_aes_hw_rv64i.inc",
    "providers/implementations/ciphers/cipher_aes_hw_s390x.inc",
    "providers/implementations/ciphers/cipher_aes_hw_t4.inc",
    "providers/implementations/ciphers/cipher_aes_ocb.inc",
    "providers/implementations/ciphers/cipher_aes_siv.inc",
    "providers/implementations/ciphers/cipher_aes_wrp.inc",
    "providers/implementations/ciphers/cipher_aes_xts.inc",
    "providers/implementations/ciphers/cipher_aes_xts_s390x.inc",
    "providers/implementations/ciphers/cipher_camellia_cts.inc",
    "providers/implementations/ciphers/cipher_camellia_hw_t4.inc",
    "providers/implementations/ciphers/cipher_chacha20.inc",
    "providers/implementations/ciphers/cipher_chacha20_poly1305.inc",
    "providers/implementations/ciphers/cipher_null.inc",
    "providers/implementations/ciphers/cipher_rc4_hmac_md5.inc",
    "providers/implementations/ciphers/cipher_sm4_ccm_hw_rv64i.inc",
    "providers/implementations/ciphers/cipher_sm4_ccm_hw_x86_64.inc",
    "providers/implementations/ciphers/cipher_sm4_gcm_hw_rv64i.inc",
    "providers/implementations/ciphers/cipher_sm4_gcm_hw_x86_64.inc",
    "providers/implementations/ciphers/cipher_sm4_hw_rv64i.inc",
    "providers/implementations/ciphers/cipher_sm4_hw_x86_64.inc",
    "providers/implementations/ciphers/cipher_sm4_xts.inc",
    "providers/implementations/ciphers/cipher_sm4_xts_hw_rv64i.inc",
    "providers/implementations/ciphers/cipher_sm4_xts_hw_x86_64.inc",
    "providers/implementations/ciphers/ciphercommon.inc",
    "providers/implementations/ciphers/ciphercommon_ccm.inc",
    "providers/implementations/ciphers/ciphercommon_gcm.inc",
    "providers/implementations/digests/blake2_prov.inc",
    "providers/implementations/digests/cshake_prov.inc",
    "providers/implementations/digests/digestcommon.inc",
    "providers/implementations/digests/mdc2_prov.inc",
    "providers/implementations/digests/ml_dsa_mu_prov.inc",
    "providers/implementations/digests/sha2_prov.inc",
    "providers/implementations/digests/sha3_prov.inc",
    "providers/implementations/encode_decode/decode_der2key.inc",
    "providers/implementations/encode_decode/decode_epki2pki.inc",
    "providers/implementations/encode_decode/decode_pem2der.inc",
    "providers/implementations/encode_decode/decode_pvk2key.inc",
    "providers/implementations/encode_decode/decode_spki2typespki.inc",
    "providers/implementations/encode_decode/encode_key2any.inc",
    "providers/implementations/encode_decode/encode_key2ms.inc",
    "providers/implementations/exchange/dh_exch.inc",
    "providers/implementations/exchange/ecdh_exch.inc",
    "providers/implementations/exchange/ecx_exch.inc",
    "providers/implementations/include/prov/blake2_params.inc",
    "providers/implementations/kdfs/argon2.inc",
    "providers/implementations/kdfs/hkdf.inc",
    "providers/implementations/kdfs/hmacdrbg_kdf.inc",
    "providers/implementations/kdfs/kbkdf.inc",
    "providers/implementations/kdfs/krb5kdf.inc",
    "providers/implementations/kdfs/pbkdf1.inc",
    "providers/implementations/kdfs/pbkdf2.inc",
    "providers/implementations/kdfs/pkcs12kdf.inc",
    "providers/implementations/kdfs/pvkkdf.inc",
    "providers/implementations/kdfs/scrypt.inc",
    "providers/implementations/kdfs/snmpkdf.inc",
    "providers/implementations/kdfs/srtpkdf.inc",
    "providers/implementations/kdfs/sshkdf.inc",
    "providers/implementations/kdfs/sskdf.inc",
    "providers/implementations/kdfs/tls1_prf.inc",
    "providers/implementations/kdfs/x942kdf.inc",
    "providers/implementations/kdfs/x963kdf.inc",
    "providers/implementations/kem/ec_kem.inc",
    "providers/implementations/kem/ecx_kem.inc",
    "providers/implementations/kem/ml_kem_kem.inc",
    "providers/implementations/kem/mlx_kem.inc",
    "providers/implementations/kem/rsa_kem.inc",
    "providers/implementations/keymgmt/dh_kmgmt.inc",
    "providers/implementations/keymgmt/dsa_kmgmt.inc",
    "providers/implementations/keymgmt/ec_kmgmt_imexport.inc",
    "providers/implementations/keymgmt/ecx_kmgmt.inc",
    "providers/implementations/keymgmt/keymgmtcommon.inc",
    "providers/implementations/keymgmt/lms_kmgmt.inc",
    "providers/implementations/keymgmt/mac_legacy_kmgmt.inc",
    "providers/implementations/keymgmt/ml_dsa_kmgmt.inc",
    "providers/implementations/keymgmt/ml_kem_kmgmt.inc",
    "providers/implementations/keymgmt/mlx_kmgmt.inc",
    "providers/implementations/keymgmt/slh_dsa_kmgmt.inc",
    "providers/implementations/keymgmt/template_kmgmt.inc",
    "providers/implementations/macs/blake2_mac_impl.inc",
    "providers/implementations/macs/cmac_prov.inc",
    "providers/implementations/macs/gmac_prov.inc",
    "providers/implementations/macs/hmac_prov.inc",
    "providers/implementations/macs/kmac_prov.inc",
    "providers/implementations/macs/poly1305_prov.inc",
    "providers/implementations/macs/siphash_prov.inc",
    "providers/implementations/rands/drbg_ctr.inc",
    "providers/implementations/rands/drbg_hash.inc",
    "providers/implementations/rands/drbg_hmac.inc",
    "providers/implementations/rands/fips_crng_test.inc",
    "providers/implementations/rands/seed_src.inc",
    "providers/implementations/rands/seed_src_jitter.inc",
    "providers/implementations/rands/test_rng.inc",
    "providers/implementations/signature/dsa_sig.inc",
    "providers/implementations/signature/ecdsa_sig.inc",
    "providers/implementations/signature/eddsa_sig.inc",
    "providers/implementations/signature/lms_signature.inc",
    "providers/implementations/signature/mac_legacy_sig.inc",
    "providers/implementations/signature/ml_dsa_sig.inc",
    "providers/implementations/signature/rsa_sig.inc",
    "providers/implementations/signature/slh_dsa_sig.inc",
    "providers/implementations/signature/sm2_sig.inc",
    "providers/implementations/skeymgmt/generic.inc",
    "providers/implementations/storemgmt/file_store.inc",
    "providers/implementations/storemgmt/file_store_any2obj.inc",
    "providers/implementations/storemgmt/winstore_store.inc",
    "providers/stores.inc",
]
// END OPENSSL SOURCE MANIFEST

// Prepared from the pinned, unmodified OpenSSL submodule. SwiftPM compiles these
// portable C sources for the destination: no binary targets or build-time tools.
let opensslTarget = Target.target(
    name: "OpenSSLCrypto",
    exclude: ["LICENSE.txt", "UPSTREAM.json"] + opensslExcludedPaths,
    sources: opensslSourcePaths,
    publicHeadersPath: "include",
    cSettings: [
        .headerSearchPath("."),
        .headerSearchPath("private"),
        .headerSearchPath("crypto"),
        .headerSearchPath("crypto/modes"),
        .headerSearchPath("providers/common/include"),
        .headerSearchPath("providers/implementations/include"),
        .headerSearchPath("providers/fips/include"),
        .define("OPENSSL_BUILDING_OPENSSL"),
        .define("OPENSSLDIR", to: "\"\""),
        .define("MODULESDIR", to: "\"\""),
        .define("NDEBUG"),
        .define("_GNU_SOURCE", .when(platforms: [.linux, .android])),
        .define("OPENSSL_APPLE_CRYPTO_RANDOM", .when(platforms: [.macOS, .iOS, .tvOS, .watchOS, .visionOS])),
    ],
    linkerSettings: [.linkedLibrary("pthread", .when(platforms: [.linux]))]
)

let package = Package(
    name: "SwiftSFTP-OpenSSL",
    platforms: [
        .macOS(.v11),
        .iOS(.v14),
        .tvOS(.v14),
        .watchOS(.v7),
        .visionOS(.v1),
        .custom("android", versionString: "28"),
    ],
    products: [.library(name: "OpenSSLCrypto", targets: ["OpenSSLCrypto"])],
    targets: [
        opensslTarget,
        .testTarget(name: "OpenSSLCryptoTests", dependencies: ["OpenSSLCrypto"]),
    ],
    swiftLanguageModes: [.v6]
)
