#pragma GCC visibility push(default)
#include <SwiftSFTP_OpenSSL/symbol_names.h>
/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2025 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef OPENSSL_ENCODERERR_H
#define OPENSSL_ENCODERERR_H
#pragma once

#include <SwiftSFTP_OpenSSL/opensslconf.h>
#include <SwiftSFTP_OpenSSL/symhacks.h>
#include <SwiftSFTP_OpenSSL/cryptoerr_legacy.h>

/*
 * OSSL_ENCODER reason codes.
 */
#define OSSL_ENCODER_R_BAD_PARAMETER_VALUE 103
#define OSSL_ENCODER_R_ENCODER_NOT_FOUND 101
#define OSSL_ENCODER_R_INCORRECT_PROPERTY_QUERY 100
#define OSSL_ENCODER_R_MISSING_GET_PARAMS 102
#define OSSL_ENCODER_R_UNKNOWN_PARAMETER_NAME 104

#endif

#pragma GCC visibility pop
